#!/usr/bin/env ansible-playbook

---

- name: Install GitLab runner
  hosts: all
  become: no  # Running as root
  gather_facts: no  # The bootstrap role gathers facts.
  strategy: free

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.buildtools
    - role: robertdebock.python_pip
    - role: robertdebock.grub
    - role: robertdebock.docker
    - role: robertdebock.users
    - role: robertdebock.gitlab_runner
    - role: robertdebock.cron
